spring:
  datasource:
    url: jdbc:h2:mem:db
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: logUser
    password: logPwd
    virtual-host: EnterpriseLog
    dynamic: true

  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
